### PR TITLE
Bug fixes

### LINKED ISSUE #65: macOS: case rename fires 2 create events
**Steps:**
* run a simple watcher as in [1]
* rename a file to same name but different case
* 🐛 2 create events are emitted when I would expect a delete and a create event

```js
const watcher = require('@parcel/watcher');

// Subscribe to events
(async function () {
    let subscription = await watcher.subscribe('<path to folder>', (err, events) => {
        console.log(events);
    });
})();
```

### LINKED ISSUE #66: Linux: deleting watched folder does not reestablish watching after re-create
I tested on Windows, macOS and Linux how the watcher behaves when the path to be watched is being deleted and found that macOS and Windows can deal with this well: when the folder is being restored, watching continues to work (at least from my basic testing that is what I figured).

But on Linux there is a delete event when the path is being deleted but the watching does not pick up again when restoring the folder.

### LINKED ISSUE #67: macOS: copying a file emits a create event for the copied file
**Steps:**
* setup the watcher to watch on a folder
* from the finder duplicate a file via copy + paste
* 🐛  you get a created event for the file that is being copied

This does not seem to happen when duplicating a folder (that is empty).

### PR DESCRIPTION
**Pull request by devongovett**
Fixes #67. Fixes #65. Fixes #66.

### CODE REVIEW

File: src/macos/FSEventsBackend.cc [hunk 1]
```diff
@@ -9,6 +9,7 @@
 #include "../Watcher.hh"
 
 #define CONVERT_TIME(ts) ((uint64_t)ts.tv_sec * 1000000000 + ts.tv_nsec)
+#define IGNORED_FLAGS (kFSEventStreamEventFlagItemIsHardlink | kFSEventStreamEventFlagItemIsLastHardlink | kFSEventStreamEventFlagItemIsSymlink | kFSEventStreamEventFlagItemIsDir | kFSEventStreamEventFlagItemIsFile)
```
Comment (bpasero) [inline src/macos/FSEventsBackend.cc:12]: It seems to me that this change could address what https://github.com/parcel-bundler/watcher/pull/57 indicated.

Comment (devongovett) [reply src/macos/FSEventsBackend.cc:12]: I believe we should actually handle those, not ignore them. We already ran into a case in parcel where writing many files quickly produces these flags and means we can't determine what changed accurately. I believe the plan is to emit a specific error code in those cases so the client can handle them. We'll work on that separately.

Comment (bpasero) [reply src/macos/FSEventsBackend.cc:12]: Yeah that makes sense. I was more referring to the extra `stat` call and handling from here:

https://github.com/parcel-bundler/watcher/blob/728b44aeec7801bae9b11e02a7fb3f0bdf94b924/src/macos/FSEventsBackend.cc#L73-L74

In case none of the expected flags are set. I think for the ones mentioned you wouldn't have to do the `stat` call to figure out the kind of event because the flags do not seem to indicate a file change.

Comment (devongovett) [reply src/macos/FSEventsBackend.cc:12]: Yeah for now what happens is it emits a `"create"` event for the root directory. Parcel currently uses that to know that it must re-build the entire project because the changes were actually unknown. When we replace that with a better error code, we can remove that.

Comment (bpasero) [reply src/macos/FSEventsBackend.cc:12]: That makes sense (though VS Code wouldn't know how to handle that actually). 

Just to clarify, you are saying that this call:

https://github.com/parcel-bundler/watcher/blob/cca5ca33483bef44246791ae30efc5d263d14429/src/macos/FSEventsBackend.cc#L76

Is being done whenever an event occurs that is none of the expected ones. But you are saying that the ones I listed in https://github.com/parcel-bundler/watcher/pull/69#discussion_r720780611 will only be emitted for the root?

Comment (devongovett) [reply src/macos/FSEventsBackend.cc:12]: Yeah that's what happens. When events are dropped, macOS emits a single event on the root directory with those flags set. At the moment since they aren't handled specially, it results in a create event because of the stat. In the future we'll emit a specific error code so clients can re-scan appropriately.

**Review by DeMoorJasper — APPROVED** [review]
