### PR TITLE
Linux: should handle `inotify_add_watch` errors more gracefully

### LINKED ISSUE #76: Linux: should handle `inotify_add_watch` errors more gracefully
This is related to https://github.com/parcel-bundler/watcher/issues/62 but not the same. It was found in https://github.com/microsoft/vscode/issues/135902 during our test week where one assignment was to test the new file watcher in VS Code. 

There is a check after `inotify_add_watch` that will throw an error when the call failed:

https://github.com/parcel-bundler/watcher/blob/f987e408cdeb6e2a66beddf82d3b1a85523942c9/src/linux/InotifyBackend.cc#L78

My understanding is that when the call-site is e.g. in a for loop (e.g. from [here](https://github.com/parcel-bundler/watcher/blob/f987e408cdeb6e2a66beddf82d3b1a85523942c9/src/linux/InotifyBackend.cc#L68-L72)), this would essentially prevent any other folders from being watched as soon as the first call to `inotify_add_watch` fails. I would argue that this needs to be handled more gracefully, i.e. not throw an error but log an error and treat this subscription specially.

To proof the point, here is a scenario where watching fails and it seems to be related to the `python3` command uses symbolic links when installing environments. Steps:
* watch a fresh empty folder and log both errors and events
* run `python3 -m venv .venv`
* you should see an error printed `inotify_add_watch failed: Not a directory` and if not please rerun until you hit this (could be a race condition)
* run `source ./.venv/bin/activate` (this might fail and require you to run `sudo apt install python3.8-venv` first)
* run `python -m pip install pip-tools`

=> 🐛  many of the file events are not visible now. If you setup file watching via `inotifywait -mr <test folder>` and run the same steps you can see how many more events are printed.

### PR DESCRIPTION
**Pull request by bpasero**
It turns out that on Linux path handling is inconsistent between the initial `subscribe` call and when a new file/folder is added under a watched folder.

In the former case, watcher seems to not attempt to watch symbolic links because of `AT_SYMLINK_NOFOLLOW`

https://github.com/parcel-bundler/watcher/blob/7d88b1c8270befe2ce06b8ddbbfb37d26bb145ea/src/unix/legacy.cc#L42

However, in the latter case, a `stat` call will resolve a symlink and then `S_ISDIR` will return true even though it is a symbolic link. Only `lstat` will preserve the stat information of the link if it is a link.

https://github.com/parcel-bundler/watcher/blob/72a57be854f6a54fbb0c11ab99a1b148ec403ed8/src/linux/InotifyBackend.cc#L161-L163

**PS:** I found more locations of `stat` that maybe need a revisit and be changed to `lstat` but I didn't attempt to do that in this PR.

This PR fixes #76

### CODE REVIEW

File: test/watcher.js [hunk 1]
```diff
@@ -383,6 +383,21 @@ describe('watcher', () => {
           let res = await nextEvent();
           assert.deepEqual(res, [{type: 'delete', path: f2}]);
         });
+
+        it.only('should not crash when a folder symlink is created', async () => {
```
Comment (devongovett) [inline test/watcher.js:387]:
```suggestion
        it('should not crash when a folder symlink is created', async () => {
```

**Review by devongovett — APPROVED** [review]
Thanks!
